version: '3'

services:
    academickeywordoccurrence:
        build: .
        tty: true
        stdin_open: true
        command: python /app/academic-keyword-occurrence/extract_occurrences.py
        volumes:
            - ./results:/app/results